### ISSUE TITLE
Unexpected error when trying to log in

### ISSUE THREAD

**Issue by macintosh-HD** [Ludy87/ecotrend-ista#128]
I was very excited to find this integration and get my heating consumption values into HA.
Unfortunately whenever I try setup the integration and setup the login I get an `Unexpected error`.
There is no further information on what went wrong.
The logger is configured like this:
```yaml
logger:
  default: warning
  logs:
    custom_components.ecotrend_ista: debug
```
But I can't find any logs from the integration.
I restarted HA multiple times and tried to log in multiple times also waiting a couple hours in between to not trigger any rate limiting on ista's side.
I have 2FA enabled in my ista account.
Anyone who can help me with this?
